language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: "OKv2NCuieMwWkqz2CmwNTK3HHtU7I1XXdPg9ZaXMa0c3ertAvmIqdj6RzRk6XfQsXJiS4DezxkJRlGx+WpASdU6gYcjFaM7V86E2BkBRV6EDCZK++5kiP+5YC7xvZ2zolStHWcuGRGgLrX3mP/Qe5NsPaAdpOL3QKzH3tZQrKS4PND4qVKwe+Yy9m/HRcGYsL4qeIk+/BVi0ZSzV0vmK5xEWvjp4+dwKdGx8vzCivZqfgZRsixigMxSRiQR4NNGPtpZUSz6gfPqHT8Wpr5UxQiShe8bf3Es5EJL2OGW4BkAPmHwlJDO6CvpTrc7rp5xFVnd31RhiiAuKpeV97necCdm5PXdKInx+G58X+M41Twf4Nsbj42yXIr72gACqPzfNl4zrhV9ZQMw6DfCsIsIxUhaMLbki66L63FkVq7H379L+wFZ+1CO+JeF6hD1qZ1hRPoz47KHmoI5mQ6jCuT7bxjijCQYFRKAXaCwWD+1oOk5CFMgXqx57EGWchArSrS97lUAEZ8XhhJzZ/8gJDT4GPsFisdeM+jLlAR9+LFhyWK21LUSrTz6uGDY/KLM8eQ4mXgZlgjwFrIlzKIepiIRfh9tAC7PGCxL+/kr2e1ePCr0dUEdFrRa/vtwDmOagHYqC5Dc6gD9vudbgDaX4UFlMnzZbOrxtPhl+yJsS0xpJiqA="
  - secure: "EzKPxGSIaf+IkqGn/dj0DE82qaDSKHiQ4yoG3C5sDxienX4vvNI/Mx51TrSm+nwmNXrdD9amVG9nTTGXiyRdY1b5ht5DSzDOpPSxdi22gZX/TVzTb4F7oJEQ73J4JOLn/RmXh7cNhUXC4GsyZ/RzFnsvRrrc98hZxK+WlUC9KHSrYYYUpYqyg1IdIyyPPQcNTMHVskioIKqey5e3NCZqh9e6Uy8zvTJl/eVQizHvOIG5PpYrvwSAzmUhO0fMEZYEsS5PB1ztN3waYxAve8ShhISFlWQ9FNn9k55fjRxdHk3qcFFGeaMKhTfAPr7eta+h5BldF1oTFuUQq0Z5Fw6EuR2WVbaG4QMIRVbZ4F7jbLVrVHrMzydHD6uWzkhXZXKJ8WbhpWqqO5rrVwDXpeMt/102Wu7ct0l2ZIz9jxEO108+KOAjbo8gVXJIAGtuEB32XxzuknYNH47q9Yg/Hq5ln0WWQo5VNj9iFY/bc8V/xq+bA0jRFfX7Sr5aZq5fpTrGG9XseSRBmMG0D7b1XHlN2eoHC6GE575RnDlMHT3pPHmdLx+CNAb5WmFu6Tl4jg5Ax2mqFspyGfTtoBuifWSMqHq7mtrrGRMbyQjJkfUJvrbU1AhomFZ18f5l92rd/DMMzp/2lAgRu0TAAgM+qGkp/E+2yJvuvzltnzKi5j+KQ3A="
  - secure: "TEehT/v+SuCdZsnNxe/uTPgqtAVemcCT5sksb3ZfOYYf0HIpIHrt5RksywIcWDneJ1y314bMy14Hbf3ITFp2sL6cvxLsZdQOmbxxGELMM4JBjef1pbzB/SMRfwyltcblNbqkNRfytBzScLJLxrn9tMdHZRn/InlZSY7R+2/+fdRyvib8mY6EdokWVn6osh0vz603jJyqBwoqklkqJNiVwOG9YxcLAlU/LmAXmvqU43qo9WN9I8gLSsP8OylWEcoW7l/8vx7PMkHoWjKDwMVCDx70PQU5B3faSY5svV131R9plX2oBdvAG3vyAYLZicisHGpOjzAP8+qhBo4+5vFG+4wwyS8JjFXidhYcBXfd+JrAR7E5JtXXFz3l+nVPpvi9pGdKZEQmWBTg5JlNjhPwY76LSP/RnPn7i2YczX2aHCRWM0XgHlY8af71ZFYA7cdqPfaPQ1krsLM5GhXIegP/hoAGLHrIkcSRbt3P3fcZAs+b7mITtTmVUxf//JXiHQbZpEMpi7QYAewPiDYZySO4+TblSvFpDFLVTKmJkygFq9Q5A4dqgCOwgL08SKOTKsUBlHCAFbpsLUKvCc8H7FucU7yVq/l4vTO0uYk0Xop0TXfkZfMXTEXCuicmlqrQXtjCOYWf0WLOKHdbIQWajE4jX3nHAyZcinAMJ52QAtlMYmA="

cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_e827c3c7d945_key -iv $encrypted_e827c3c7d945_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi